services:
  db:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=328221

  api:
    build: ./api
    ports:
      - 5000:5000
    depends_on:
      - db
